fix

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -18,3 +18,9 @@ jobs:
           echo "Sleeping for 30 seconds..."
           sleep 30
           echo "Done test!"
+
+      # 3. エラーを発生させる
+      - name: Fail intentionally
+        run: |
+          echo "Intentionally failing this job."
+          exit 1
